# Generated by Django 5.2.3 on 2025-07-01 15:08

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('activity_level', models.FloatField(choices=[(1.2, 'Sedentary'), (1.375, 'Light exercise'), (1.55, 'Moderate exercise'), (1.725, 'Heavy exercise'), (1.9, 'Very heavy exercise')], default=1.2)),
                ('age', models.IntegerField()),
                ('weather_condition', models.CharField(choices=[('hot', 'Hot'), ('mild', 'Mild'), ('cold', 'Cold')], default='mild', max_length=10)),
                ('custom_daily_goal', models.FloatField(blank=True, help_text='Custom daily water goal in ml', null=True)),
                ('glass_volume', models.IntegerField(default=250, help_text='Default glass volume in ml')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Amount in ml')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_consumed', models.IntegerField(default=0, help_text='Total consumed in ml')),
                ('goal_amount', models.IntegerField(default=0, help_text='Goal amount for this day in ml')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
