# Generated by Django 5.2.3 on 2025-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Cairo', help_text='Your city for weather-based goal calculation', max_length=100),
        ),
    ]
